"""feat: add queries table for translation history tracking

Revision ID: 962f773da434
Revises: a1b2c3d4e5f6
Create Date: 2026-01-12 05:40:38.783672

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "962f773da434"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "queries",
        sa.Column("query_id", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("neo4j_connection_id", sa.Integer(), nullable=True),
        sa.Column("sql_query", sa.Text(), nullable=False),
        sa.Column("cypher_query", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("TRADUCIDO", "EJECUTADO", "FALLIDO", name="querystatus"),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "translation_time",
            sa.Float(),
            nullable=True,
            comment="Tiempo de traducción en milisegundos",
        ),
        sa.Column(
            "execution_time",
            sa.Float(),
            nullable=True,
            comment="Tiempo de ejecución en milisegundos",
        ),
        sa.Column(
            "nodes_affected",
            sa.Integer(),
            nullable=True,
            comment="Número de nodos afectados en la ejecución",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["neo4j_connection_id"],
            ["connections.connection_id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("query_id"),
    )
    op.create_index(
        op.f("ix_queries_neo4j_connection_id"),
        "queries",
        ["neo4j_connection_id"],
        unique=False,
    )
    op.create_index(op.f("ix_queries_query_id"), "queries", ["query_id"], unique=False)
    op.create_index(op.f("ix_queries_status"), "queries", ["status"], unique=False)
    op.create_index(op.f("ix_queries_user_id"), "queries", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_queries_user_id"), table_name="queries")
    op.drop_index(op.f("ix_queries_status"), table_name="queries")
    op.drop_index(op.f("ix_queries_query_id"), table_name="queries")
    op.drop_index(op.f("ix_queries_neo4j_connection_id"), table_name="queries")
    op.drop_table("queries")
    # ### end Alembic commands ###
