"""feat: add connections table for database configurations

Revision ID: a1b2c3d4e5f6
Revises: 0d90a6dd94b8
Create Date: 2026-01-12 10:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, Sequence[str], None] = "0d90a6dd94b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connections",
        sa.Column("connection_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("conn_name", sa.String(length=100), nullable=False),
        sa.Column(
            "db_type",
            sa.Enum("SQL_SERVER", "NEO4J", name="databasetype"),
            nullable=False,
        ),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("db_user", sa.String(length=255), nullable=False),
        sa.Column("db_password", sa.String(length=512), nullable=False),
        sa.Column("database_name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("connection_id"),
    )
    op.create_index(
        op.f("ix_connections_connection_id"),
        "connections",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_connections_user_id"), "connections", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_connections_user_id"), table_name="connections")
    op.drop_index(op.f("ix_connections_connection_id"), table_name="connections")
    op.drop_table("connections")
    op.execute("DROP TYPE databasetype")
    # ### end Alembic commands ###
